### ISSUE TITLE
Problems getting data

### ISSUE THREAD

**Issue by kassoren** [kpoppel/homeassistant-eforsyning#23]
Hey

I have tried almost everything to get this component to work..

I’ve tried to install 0.5 to 0.9 and I have tried to install 0.9 atleast 10 times (deleting, installing, etc.)

No errors in the setup process, I get a successful installation every time. I checked the supplier-Id, username and password many times, no difference.. also tried with and with out the billing “check” (July to June)

When I set up my card it keeps showing like this:
![919F8839-F31E-46F6-9445-809C98D2D26B](https://user-images.githubusercontent.com/99141498/180968801-7db75edc-f208-4241-8566-a5541a764733.jpeg)

Thank you very much

**Comment by kassoren** [comment]
I'm not that much into the coding, however I just tried adding an "ApexCharts-Card" with this code:

```
type: custom:apexcharts-card
header:
  show: true
  title: ApexCharts-Card
  show_states: true
  colorize_states: true
series:
  - entity: sensor.fjernvarme_water_temperature_forward
    data_generator: |
      // REMOVE ME
      const now = new Date();
      const data = [];
      for(let i = 0; i <= 24; i++) {
        data.push([now.getTime() - i * 1000 * 60 * 60, Math.floor((Math.random() * 10) + 1)])
      }
      return data.reverse();
  - entity: sensor.fjernvarme_water_temperature_return
    type: column
    data_generator: |
      // REMOVE ME
      const now = new Date();
      const data = [];
      for(let i = 0; i <= 24; i++) {
        data.push([now.getTime() - i * 1000 * 60 * 60, Math.floor((Math.random() * 10) + 1)])
      }
      return data.reverse();
```

Now I'm actually getting some data for the first time. However the data doesn't make sense compared to what I see on eforsyning when i log in.

![fjernvarme](https://user-images.githubusercontent.com/99141498/180991376-2cc6b2e1-a734-4df6-ac66-1518eedaf75e.PNG)

Best regards.

**Comment by kpoppel** [comment]
What you are seeing with the Apex chart code above is not eForsyning data but random numbers generated by these lines.

```data_generator: |
      // REMOVE ME
      const now = new Date();
      const data = [];
      for(let i = 0; i <= 24; i++) {
        data.push([now.getTime() - i * 1000 * 60 * 60, Math.floor((Math.random() * 10) + 1)])
      }
      return data.reverse();
```

So back to your original issue...

1. First of all, give it 24h to update.
2. If you still see no result (or just do it right now), add the debug lines mentioned in the README.md file to `configuration.yaml,` and post the result here - remember to remove account information as this is also dumped in the log with debugging turned on.
3. If we cannot see what's going on there, the next step is to change another file a little: https://github.com/kpoppel/homeassistant-eforsyning/blob/main/custom_components/eforsyning/__init__.py. Copy line 95 below line 93 and comment out the rest with #

**Comment by kassoren** [comment]
Thanks for the quick response :)

This is the only line I could fine in the log that looks a little bit out of the ordinary:
`2022-07-26 17:25:29 WARNING (SyncWorker_3) [custom_components.eforsyning] Exception: <class 'ValueError'>`

I dont see any account information

**Comment by kassoren** [comment]
Now something happened. I'm getting the exact same error for all 14 sensors, its looking like this for each sensor:

`2022-07-26 17:33:58 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.eforsyning_water_end fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 514, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 709, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/eforsyning/sensor.py", line 133, in update
    self._data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 192, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/eforsyning/__init__.py", line 94, in update
    data = self._client.get_latest()
  File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 277, in get_latest
    r = self._parse_result(json_response)
  File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 330, in _parse_result
    metering_data['extra-end'] = self._stof(reading['Slut'])
  File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 293, in _stof
    return float(fstr.replace(',', '.'))
ValueError: could not convert string to float: ''

**Comment by kpoppel** [comment]
Okay, that looks interesting.  Could you do part 2 with the __init__.py file, please.  This removes the try: catch: part which basically occludes all the interesting stuff.  Also add the debug statements and post the result here.
Somewhere you may get connected but the data retrieved does not look like the program expects.

**Comment by kassoren** [comment]
Okay so just to be sure:

You want me to add the following lines:

`logger: 
  default: info
  logs: 
    pyeforsyning.eforsyning: debug`

And you want me to add them in:
custom_components/eforsyning/pyeforsyning/__init__.py

And then I might find some new logs in home-assistant.log that I can post here, right?

Thank you very much

**Comment by kassoren** [comment]
I just did what I was texting above, and now I'm getting this (But not the other errors from before):

```
2022-07-26 18:15:15 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing component custom_components.eforsyning
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 599, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/eforsyning/__init__.py", line 10, in <module>
    from custom_components.eforsyning.pyeforsyning.eforsyning import Eforsyning
  File "/config/custom_components/eforsyning/pyeforsyning/__init__.py", line 11
    logger: 
            ^
SyntaxError: invalid syntax
2022-07-26 18:15:15 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration eforsyning: Unable to import component: Exception importing custom_components.eforsyning
```

But now it also says "Not loaded" which I havent seen before.

Could this be because that i copied that line 95 and put below line 93?

![loaded](https://user-images.githubusercontent.com/99141498/181059156-50c3bd9a-8b3c-4dd2-b6b1-a0922ddbcf6c.PNG)

Update: Just tried to remove the copied line again and "uncomment" the lines below. But same error and it still says "Not loaded". I have of course restartet HA a couple of times. I'm stocked :/

**Comment by kpoppel** [comment]
You are half-way there :-)  It should look like this (https://github.com/kpoppel/homeassistant-eforsyning/blob/main/custom_components/eforsyning/__init__.py):
```
    @Throttle(MIN_TIME_BETWEEN_UPDATES)
    def update(self):
        _LOGGER.debug("Fetching data from Eforsyning")
        data = self._client.get_latest()
 
#        try: 
#            data = self._client.get_latest()
#            if data.status == 200:
#                self._data = data
#            else:
#                _LOGGER.warn(f"Error from eforsyning: {data.status} - {data.detailed_status}")
#        except requests.exceptions.HTTPError as he:
#            message = None
#            if he.response.status_code == 401:
#                message = f"Unauthorized error while accessing eforsyning.dk. Wrong or expired refresh token?"
#            else:
#                message = f"Exception: {e}"
#
#            _LOGGER.warn(message)
#        except: 
#            e = sys.exc_info()[0]
#            _LOGGER.warn(f"Exception: {e}")

        _LOGGER.debug("Done fetching data from Eforsyning")
```

**Comment by kpoppel** [comment]
As for the `configuration.yaml` file you just copy the lines exactly as in the README.md file.  Example:

```
# Top of file
default_config:

logger: 
  default: info
  logs: 
    pyeforsyning.eforsyning: debug

# The rest of the file
```

**Comment by kassoren** [comment]
Looks like the same error:

```
2022-07-26 18:52:48 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing component custom_components.eforsyning
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 599, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/eforsyning/__init__.py", line 10, in <module>
    from custom_components.eforsyning.pyeforsyning.eforsyning import Eforsyning
  File "/config/custom_components/eforsyning/pyeforsyning/__init__.py", line 11
    logger: 
            ^
SyntaxError: invalid syntax
2022-07-26 18:52:48 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration eforsyning: Unable to import component: Exception importing custom_components.eforsyning
```
When i add the lines:

```
logger: 
  default: info
  logs: 
    pyeforsyning.eforsyning: debug
```

**in pyeforsyning/init.py** (they are still added in configuration.yalm)

The component will show as **"Not loaded"**

Errors will still be the same when i put those lines in one of the init.py

I'm not seeing any account information (credentials) in the log at any time.

**Comment by kassoren** [comment]
I might have found something but i dont know what :P  (**Update: Probably nothing to do with this**)

Forgot to paste one line above the other lines with errors (Marked Bold here):

**2022-07-26 19:44:03 WARNING (MainThread) [homeassistant.components.hassio] Could not fetch stats for a0d7b954_ssh: Container addon_a0d7b954_ssh is not running**
2022-07-26 19:44:06 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing component custom_components.eforsyning
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 599, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/eforsyning/__init__.py", line 10, in <module>
    from custom_components.eforsyning.pyeforsyning.eforsyning import Eforsyning
  File "/config/custom_components/eforsyning/pyeforsyning/__init__.py", line 5
    logger: 
            ^
SyntaxError: invalid syntax
2022-07-26 19:44:06 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration eforsyning: Unable to import component: Exception importing custom_components.eforsyning

**Comment by kpoppel** [comment]
The `logger` lines must go into the `configuration.yaml` file.  Like this:
![image](https://user-images.githubusercontent.com/4174578/181075627-a290a7e2-f238-4530-9382-3daf19a52d1d.png)

Installing the VScode server is really useful:
![image](https://user-images.githubusercontent.com/4174578/181075832-a5d2c50d-24c3-4e6c-bc61-0c6df27688ff.png)

**Comment by kassoren** [comment]
Thats how it is right now :)
![logger](https://user-images.githubusercontent.com/99141498/181076358-1fea35c1-0bc7-40e5-9613-51c562ede502.PNG)

Error1:
Logger: homeassistant.setup
Source: setup.py:162
First occurred: 19:52:14 (1 occurrences)
Last logged: 19:52:14

Setup failed for custom integration eforsyning: Unable to import component: Exception importing custom_components.eforsyning

Error2:
This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/eforsyning/__init__.py:10
Integration: EForsyning
First occurred: 19:52:14 (1 occurrences)
Last logged: 19:52:14

Unexpected exception importing component custom_components.eforsyning
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 599, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/eforsyning/__init__.py", line 10, in <module>
    from custom_components.eforsyning.pyeforsyning.eforsyning import Eforsyning
  File "/config/custom_components/eforsyning/pyeforsyning/__init__.py", line 5
    logger: 
            ^
SyntaxError: invalid syntax

**Comment by kpoppel** [comment]
It looks like the same lines appear in the `__init__.py` file as well?  Maybe a screen sharing session would be quicker :-)

**Comment by kassoren** [comment]
Haha :-) that would definetely be easier.

thought you wanted me to put the debugging lines in both configuration.yalm and init.py?

or what did you mean with:
Okay, that looks interesting. Could you do part 2 with the init.py file, please. This removes the try: catch: part which basically occludes all the interesting stuff. Also add the debug statements and post the result here.
Somewhere you may get connected but the data retrieved does not look like the program expects.

**Comment by kpoppel** [comment]
In `__init__.py`Just the code changes listed in https://github.com/kpoppel/homeassistant-eforsyning/issues/23#issuecomment-1195709236
And the other change only in `configuration.yaml` :-)

**Comment by kassoren** [comment]
I went through it all again:

Getting this error again:
2022-07-26 20:05:46 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.eforsyning_water_temperature_exp_return fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 514, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 709, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/eforsyning/sensor.py", line 133, in update
    self._data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 192, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/eforsyning/__init__.py", line 93, in update
    data = self._client.get_latest()
  File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 277, in get_latest
    r = self._parse_result(json_response)
  File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 330, in _parse_result
    metering_data['extra-end'] = self._stof(reading['Slut'])
  File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 293, in _stof
    return float(fstr.replace(',', '.'))
ValueError: could not convert string to float: ''

**Comment by kpoppel** [comment]
okay, maybe a screen share? :-)  https://remotedesktop.google.com/?pli=1 could be a way.

**Comment by kassoren** [comment]
Yes please :)

**Comment by kpoppel** [comment]
Thanks for sharing your data with me.  I have the debug output on my dev-instance of HA 2022.7.7 and with this I found out what is going on.

```
    "TForbrugsTaellevaerk": [
     {
      "IndexNavn": "M3",  <---This one is parsed - all numbers are floats
      "Enhed_Txt": "m³",
      "Korrig": "0,00",
      "Beskrivelse": "M3",
      "Enhed": "1",
      "Faktor": "1",
      "Slut": "2551,11",
      "Start": "2550,77",
      "Format": "####0.00",
      "Forbrug": "0,34"
     },{
      "IndexNavn": "ENG1", <--- This one is parsed, all numbers are floats
      "Enhed_Txt": "MWh",
      "Korrig": "0,000",
      "Beskrivelse": "Energi",
      "Enhed": "7",
      "Faktor": "1",
      "Slut": "115,453",
      "Start": "115,446",
      "Format": "##0.000",
      "Forbrug": "0,007"
     },{
      "IndexNavn": "TIME_", <-- This one is also parsed, except one number is not a float
      "Enhed_Txt": "Timer",
      "Korrig": "0,00",
      "Beskrivelse": "Tid",
      "Enhed": "20",
      "Faktor": "1",
      "Slut": "",    <- Expect this one to contain a float value... Which it is not obviously.
      "Start": "62136,00",
      "Format": "####0.00",
      "Forbrug": "0"
     }
```

With the release I will make in a few minutes, Home Assistant reports:
![image](https://user-images.githubusercontent.com/4174578/181114800-74800a05-9dbb-4778-bd8c-efa21c0434e1.png)

While the web UI reports:
![image](https://user-images.githubusercontent.com/4174578/181114861-ed203007-b712-4030-8b17-9f8cd10f3908.png)

I noticed in the dataset that this _TIME field is something I don't have in my dataset.  I suppose this is for the hour-readout of your metering device.  Not of much use in HA, as it just counts the hours since the device was started.  Nevertheless this was the source of error.

**Comment by kpoppel** [comment]
Fixed by [Release v0.9.1](https://github.com/kpoppel/homeassistant-eforsyning/releases/tag/v.0.9.1)

**Comment by kassoren** [comment]
Awesome! Once again thanks alot!..

Have you tried to pull water usage from eforsyning as well? I can see that both my "Fjernvarme-selskab" and "Vandværk" is using it :)

**Comment by kassoren** [comment]
And sorry, but last question

Is it correct that initially, it will look like this? (And then i guess it will start getting the different values over time :))
![forbrug](https://user-images.githubusercontent.com/99141498/181121824-7b3280cc-7e33-4361-8f61-0e416b9fec86.PNG)

**Comment by kpoppel** [comment]
Definitely. Here is a screenshot from InfluxDB reaching back to June 11 on my end.:
![image](https://user-images.githubusercontent.com/4174578/181175961-14f1758c-4cf9-4604-a299-932d71d427af.png)

Re. reading water I haven't tried that.  I am on Novafos (my other plugin), but wouldn't mind taking a look.  Please open a new issue on water and let's discuss that if loading another instance of the module does not work right out of the box.  It might :-)

**Comment by kassoren** [comment]
I’ll try reading the water.. seems to work so far 👍.. However theres a lot of entities that are not beeing used.. probably only 4 of them.. but i guess people can delete themselves.. 

Ill get back if I discover any issues

thanks
