### ISSUE TITLE
Not working after core update

### ISSUE THREAD

**Issue by hedevej41** [kpoppel/homeassistant-eforsyning#25]
Eforsyning er holdt op med at virke efter core update 2022.8.6. får unknown sensore men ingen fejl i loggen

**Comment by Bluhme1** [comment]
også her.

Har en fejl i loggen


Logger: homeassistant.helpers.entity
Source: custom_components/eforsyning/pyeforsyning/eforsyning.py:227 
Integration: EForsyning 
First occurred: 20.54.01 (286 occurrences) 
Last logged: 21.00.01

Update for sensor.eforsyning_water_used fails
Update for sensor.eforsyning_water_exp_used fails
Update for sensor.eforsyning_water_start fails
Update for sensor.eforsyning_water_end fails
Update for sensor.eforsyning_water_exp_end fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 514, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 709, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/eforsyning/sensor.py", line 180, in update
    self.coordinator.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 192, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/eforsyning/__init__.py", line 93, in update
    self.data = self._client.get_latest()
  File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 271, in get_latest
    if not self._get_access_token():
  File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 227, in _get_access_token
    result = requests.get(security_token_url)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by hedevej41** [comment]
efter genstart af ha fk jeg så fejl i loggen

2022-08-19 19:31:23.123 INFO (MainThread) [homeassistant.setup] Setting up eforsyning
2022-08-19 19:31:23.124 INFO (MainThread) [homeassistant.setup] Setup of domain eforsyning took 0.0 seconds
2022-08-19 19:31:23.541 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.eforsyning
File "/config/custom_components/eforsyning/sensor.py", line 180, in update
File "/config/custom_components/eforsyning/__init__.py", line 93, in update
File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 271, in get_latest
File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 227, in _get_access_token
File "/config/custom_components/eforsyning/sensor.py", line 180, in update
File "/config/custom_components/eforsyning/__init__.py", line 93, in update
File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 271, in get_latest
File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 227, in _get_access_token
File "/config/custom_components/eforsyning/sensor.py", line 180, in update
File "/config/custom_components/eforsyning/__init__.py", line 93, in update
File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 271, in get_latest
File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 227, in _get_access_token
File "/config/custom_components/eforsyning/sensor.py", line 180, in update
File "/config/custom_components/eforsyning/__init__.py", line 93, in update
File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 271, in get_latest
File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 227, in _get_access_token
File "/config/custom_components/eforsyning/sensor.py", line 180, in update
File "/config/custom_components/eforsyning/__init__.py", line 93, in update
File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 271, in get_latest
File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 227, in _get_access_token
File "/config/custom_components/eforsyning/sensor.py", line 180, in update
File "/config/custom_components/eforsyning/__init__.py", line 93, in update
File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 271, in get_latest
File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 227, in _get_access_token
File "/config/custom_components/eforsyning/sensor.py", line 180, in update
File "/config/custom_components/eforsyning/__init__.py", line 93, in update
File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 271, in get_latest
File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 227, in _get_access_token
File "/config/custom_components/eforsyning/sensor.py", line 180, in update
File "/config/custom_components/eforsyning/__init__.py", line 93, in update
File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 271, in get_latest
File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 227, in _get_access_token
File "/config/custom_components/eforsyning/sensor.py", line 180, in update
File "/config/custom_components/eforsyning/__init__.py", line 93, in update
File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 271, in get_latest
File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 227, in _get_access_token
File "/config/custom_components/eforsyning/sensor.py", line 180, in update

og sådan bliver det ved i flere hundrede linier

**Comment by Bluhme1** [comment]
@hedevej41 Kan du logge ind på appen når du er på Wifi. Jeg kan kun når jeg er på 5G.
Kan vores IP være blevet blokeret fordi vi har haft for mange kald?

**Comment by hedevej41** [comment]
@Bluhme1 jeg er ved at tro at du har ret. jeg kan ikke logge på eforsyning hverken via browser eller via app når jeg er på lokal lan men via mobil net kan jeg godt

**Comment by Bluhme1** [comment]
Vi må så rette henvendelse til den lokale forsyning, og blive "unbanned" men vi skal jo være sikre på at det ikke sker igen

**Comment by hedevej41** [comment]
@Bluhme1 de må jo have et eller andet max antal kald som gør at man bliver banned

**Comment by Bluhme1** [comment]
ja. vi må kontakte dem i næste uge. Er desværre bortrejst hele ugen men hører gerne, hvis du finder ud af noget

**Comment by hedevej41** [comment]
@Bluhme1 der er gang i en tråd på dansk homeassistant gruppe på facebook hvor flere har samme problem som os hvor deres ip til hjemmet er blokeret til eforsyning men de kan godt logge på via mobil netværk. så integrationen må jo simpelhem lave alt for mange kald til eforsyning

**Comment by kpoppel** [comment]
Jeg kan bekræfte at jeg selv ser samme fejl.

Som det kan ses her: https://github.com/kpoppel/homeassistant-eforsyning/blob/main/custom_components/eforsyning/const.py

Er det i hvert fald meningen at integration ikke rammer APIet oftere end hver 6. time.

Min første observation i loggen er for 3 dage siden.
```
2022-08-17 16:12:16.734 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.eforsyning_water_temperature_cooling fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 514, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 709, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/eforsyning/sensor.py", line 180, in update
    self.coordinator.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 192, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/eforsyning/__init__.py", line 93, in update
    self.data = self._client.get_latest()
  File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 271, in get_latest
    if not self._get_access_token():
  File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 234, in _get_access_token
    result_json = result.json()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Bedste ting at gøre lige nu, er at deaktivere integrationen.  Og så enten ringe til eForsyning og få IP-ban ophævet, eller vente på at det sker af sig selv forhåbentlig.

**Comment by kpoppel** [comment]
En anden observation hos mig er, at heller ikke via eks. mobilt hotspot, kan jeg logge ind.  https://api2.dff-edb.dk (som login token skal hentes fra) svarer ikke på noget som helst.

https://eforsyning.dk/brugermoede/driftsstatus/  ser nu også en kende morsom ud..

![image](https://user-images.githubusercontent.com/4174578/185716497-e440e045-bb7c-430c-846e-eaf9cc907bd8.png)


Edit:
Det ser ud til at også andre fjernvarme-selskaber ser samme problem med api2... overover.  I kommunikationen sendes der logs til  webhook.logentries.com som bl.a. indeholder  "Warning, Besked: "Http failure for htps://api2...: 0 Unknown Error"
Ping via eks. [site24x7](https://www.site24x7.com/ping-test.html) viser også dette endpoint som utilgængeligt.

Som udgangspunkt vil jeg sige, at integrationen ikke gør noget forkert, men samtidig er der måske noget den kan gøre lidt bedre :-) Det jeg måske kan gøre, er at teste om api2... er oppe, og hvis ikke, lade være med at prøve flere gange.  Det vil da spare loggen fra flere 1000 linjer fejlmeddelelser.

**Comment by kpoppel** [comment]
FYI, så arbejder jeg på en opdatering der vil undlade at ramme APIet for hver eneste sensor der registreres.  Jeg mener jeg har løsningen på min anden integration "novafos" til øjensynligt at køre.  Det er bare lidt svært på eForsyning så længe APIet ikke er tilgængeligt.

**Comment by hedevej41** [comment]
@kpoppel jeg deaktiverede integrationen i aftes. og her til aften kunne jeg igen logge på eforsyning via browser. jeg aktiverede så integrationen igen. og data kom ikke ind og nu kan jeg igen ikke logge på via browser. så integrationen må lave et eller andet som deres api ikke kan li

**Comment by kpoppel** [comment]
Tak for opdateringen.  Jeg tænker et problem kan være det, at API et bliver kaldt for hver eneste sensor i hurtig rækkefølge.  Det er jo noget der har fungeret i meget lang tid, men måske har de ændret i noget vedr. dette.
Heldigvis henter dette ene kald data for samtlige sensorer, så det kan reduceres til at ramme APIet 1 gang per 6 timer i stedet for de her 20 eller 27 gange hvis man både har varme og vand fra eForsyning.

Jeg giver lige besked her på issuet når der er en release klar.

**Comment by kpoppel** [comment]
Release v0.11.0 er ude.  Hvis I er villige til at teste den, vil det hjælpe.
Ideen er, at integrationen kun laver en enkelt request hver 6. time til at samle data for samtlige sensorer.
Om API severen så også tjekker på eks. Browser headers, ved jeg ikke, så længe jeg selv er låst ude.  Men noget er jo anderledes.

**Comment by heinekmadsen** [comment]
Jeg har forsøgt mig med 0.11.0 og får denne fejl ved konfigurationen af integrationen
![image](https://user-images.githubusercontent.com/48906528/185882257-abaa2bb1-a50b-4763-9bd3-2116b870994f.png)

**Comment by Bluhme1** [comment]
Jeg har været i kontakt med mit forsyningsselskab. De betragter denne integration som et forsøg på hacking og har meldt det til Datatilsynet. Der var endda også tale om en evt. politianmeldelse.
Jeg forklarede sammenhængen og fortalte om Home Assistant og vores arbejde med dette. Det formildede dem en del (altså ingen ond vilje) men mente at vi skulle være forsigtige i fremtiden. Evt. kontakte IT firmaet der står for API’en og forklare vores hensigter.
Firmaet hedder Softvaerket.dk 

https://www.softvaerket.dk/media/2861/generelt-om-funktionerne.pdf

Ja, ja man kan hurtigt komme galt afsted 😱😱

**Comment by ElwayDenmark** [comment]
jeg ved ikke om det er relateret - men jeg ville gerne prøve denne integration, men kan slet ikke fremsøge den i HACS. Om det er relateret til ovenstående problem, vej jeg ikke. Er på HA 2022.8.6 version

**Comment by kpoppel** [comment]
@Bluhme1 , Jeg er også selv blevet ringe op af det lokale værk, og kunne i den forbindelse også fortælle at der ikke er tale om forsøg på brud på sikkerheden.  Det var de noget lettede over.  Det fremgik af samtalen at Softværket nok er begyndt at se på antallet af login, og spærrer de IP-adresser hvor der er mistænkeligt mange af slagsen på kort tid.  Det er jo fuldstændig fair.  Jeg har også fået snakket med en venlig mand fra Softværket, som er glad for at det er legitim kommunikation det handler om.  Jeg har tilbudt at gennemgå koden med en af deres udviklere, så alt er i det åbne.

Hvis nogle fra Softværket læser med, undskylder jeg mange gange for de mange requests og for at trigge Jeres beredskabsplan på den måde.
I seneste iteration, vil der kun være 1 request per 6 timer på kørende installationer.

**Comment by kpoppel** [comment]
@ElwayDenmark , du skal selv tilføje repository i HACS som det er lige nu.  Der er en proces i gang for at få det med i HACS default.

**Comment by kpoppel** [comment]
@heinekmadsen Prøv v0.11.1.  Der var en tastefejl kan jeg se.

**Comment by Sdahl1234** [comment]
Jeg har fået åbnet for min ip igen og kan bekræfte at v.0.10.0 virker men v.0.11.1 giver ingen fejl ej heller nogle data.

**Comment by kpoppel** [comment]
@Sdahl1234 Tak for feedback.  Nu ved de hvad der foregår, så måske er det ok at bruge v0.10.0 . Jeg vil nok foreslå at disable indtil jeg har en fungerende v0.11.x klar.  Bare for at være rare ved Softværkets overvågningssystem :-)
Jeg har ikke rigtig kunnet teste vejen fra API request til data ankommer i HA  med min egen IP blokeret.  Det håber jeg er muligt i eftermiddag engang.

**Comment by Bluhme1** [comment]
Er blevet kontaktet af fjernvarmeværket igen. Det er nu mere ro på, idet de har fundet ud af, hvad der er på færde. 
Anmeldelsen tul Datatilsynet er trukket tilbage og polianmeldelsen bliver heller ikke aktuel.
Så nu er paraderne sænket lidt

**Comment by kpoppel** [comment]
OpenSource har aldrig været mere spændende :-)

**Comment by kpoppel** [comment]
Release [v0.11.2](https://github.com/kpoppel/homeassistant-eforsyning/releases/tag/v0.11.2) er klar.  Nu har jeg set data komme ind hos mig selv, på en enkelt request.
Hvis der er andre problemer, så tager vi den i et nyt issue.  Dette her er et til historiebøgerne.

**Comment by Symbiot78** [comment]
efter update og genstart:

 File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/eforsyning/coordinator.py", line 55, in _async_update_data
    raise ConfigEntryNotReady from error
homeassistant.exceptions.ConfigEntryNotReady: 'energy-tv2-start'

**Comment by Sdahl1234** [comment]
v0.11.2 virker hos mig :-)

**Comment by hedevej41** [comment]
efter update og genstart

This error originated from a custom integration.

Logger: custom_components.eforsyning.coordinator
Source: custom_components/eforsyning/coordinator.py:55
Integration: EForsyning (documentation, issues)
First occurred: 16:46:29 (5 occurrences)
Last logged: 16:52:17

Unexpected error fetching eForsyning data: 'energy-tv2-start'
Unexpected error fetching eForsyning data: 'NoneType' object has no attribute 'raise_for_status'
Traceback (most recent call last):
  File "/config/custom_components/eforsyning/coordinator.py", line 53, in _async_update_data
    data = await self.hass.async_add_executor_job(self.api.get_latest)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 316, in get_latest
    result = self._parse_result_heating(raw_data)
  File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 412, in _parse_result_heating
    "kWh-TV2-Start" : metering_data['energy-tv2-start'],
KeyError: 'energy-tv2-start'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/eforsyning/coordinator.py", line 55, in _async_update_data
    raise ConfigEntryNotReady from error
homeassistant.exceptions.ConfigEntryNotReady: 'energy-tv2-start'

**Comment by Bluhme1** [comment]
@kpoppel ja. Det glemmer vi aldrig og det bliver en  “vandrehistorie” i Home Assistant miljøet.
Men tak for indsatsen

**Comment by hedevej41** [comment]
@kpoppel tak. har disabled det i eforsyning.py og nu har jeg hul igennem. tak for indsatsen :-)
