### ISSUE TITLE
Data field "energy-tv2-start" does not exist in some installations.

### ISSUE THREAD

**Issue by kpoppel** [kpoppel/homeassistant-eforsyning#26]
efter update og genstart

This error originated from a custom integration.

Logger: custom_components.eforsyning.coordinator
Source: custom_components/eforsyning/coordinator.py:55
Integration: EForsyning (documentation, issues)
First occurred: 16:46:29 (5 occurrences)
Last logged: 16:52:17

Unexpected error fetching eForsyning data: 'energy-tv2-start'
Unexpected error fetching eForsyning data: 'NoneType' object has no attribute 'raise_for_status'
Traceback (most recent call last):
  File "/config/custom_components/eforsyning/coordinator.py", line 53, in _async_update_data
    data = await self.hass.async_add_executor_job(self.api.get_latest)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 316, in get_latest
    result = self._parse_result_heating(raw_data)
  File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 412, in _parse_result_heating
    "kWh-TV2-Start" : metering_data['energy-tv2-start'],
KeyError: 'energy-tv2-start'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/eforsyning/coordinator.py", line 55, in _async_update_data
    raise ConfigEntryNotReady from error
homeassistant.exceptions.ConfigEntryNotReady: 'energy-tv2-start'

_Originally posted by @hedevej41 in https://github.com/kpoppel/homeassistant-eforsyning/issues/25#issuecomment-1222474529_

**Comment by kpoppel** [comment]
@hedevej41
Okay, den er ny.  Det ser ud til at du ikke har TV2 data fra din måler.  Det retter jeg, så der så også tages højde for at måske TV2 og ENG2, som er seneste tilføjelser ikke skulle eksistere.

**Comment by kpoppel** [comment]
Fixed by [v0.11.3](https://github.com/kpoppel/homeassistant-eforsyning/releases/tag/v0.11.3)

**Comment by hedevej41** [comment]
@kpoppel  jep det virker :-)
