### ISSUE TITLE
Efter Update til nyeste version virker sensorer for vand ikke

### ISSUE THREAD

**Issue by Bluhme1** [kpoppel/homeassistant-eforsyning#29]
Spændende med billing funktionalitet 
Efter opdatering virker mine vand-entiteter ikke. Varme entiteter er ok (tror jeg)
Se fejlkoder:

Logger: homeassistant.components.sensor
Source: custom_components/eforsyning/sensor.py:187 
Integration: Sensor (documentation, issues) 
First occurred: 22.36.38 (4 occurrences) 
Last logged: 23.12.06

Error adding entities for domain sensor with platform eforsyning
Error while setting up eforsyning platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 673, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 776, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 573, in _async_write_ha_state
    attr.update(self.extra_state_attributes or {})
  File "/config/custom_components/eforsyning/sensor.py", line 187, in extra_state_attributes
    self._attrs["billing"] = self._sensor_data["billing"]
KeyError: 'billing'

**Comment by kpoppel** [comment]
Ah ja, jeg ved hvor. Downgrade til v0.11.3, så fikser jeg det. Regnskab er ikke med på vand, da jeg ikke ved hvordan de data ser ud 😏

**Comment by kpoppel** [comment]
Release v1.0.0 er ude.  Fejlen her skulle være fikset.  Hvis det virker, er du velkommen til at lukke issuet. Bemærk releasen er ikke bagudkompatibel pga. #30 som også kom med.

**Comment by Bluhme1** [comment]
Desværre. Der kommer stadig ingen entiteter fra vand-delen. Derfor kan jeg heller ikke sige, om de er korrekte eller ej (#28). Så jeg lader dem begge være åbne

Får følgende fejlmeddelelse

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 673, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 777, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 574, in _async_write_ha_state
    attr.update(self.extra_state_attributes or {})
  File "/config/custom_components/eforsyning/sensor.py", line 166, in extra_state_attributes
    "value" : data_point[self.entity_description.attribute_data],
KeyError: 'M3-'

**Comment by kpoppel** [comment]
Det er lidt at fægte i mørket når jeg ikke selv har adgang til de her data. Jeg tager en runde mere. Tak for at du tester det af.  På et tidspunkt må det jo blive rigtigt.

**Comment by Bluhme1** [comment]
Ja, det forstår jeg godt. Sig til hvis du behøver flere data.
Vi skal nok komme i mål

**Comment by kpoppel** [comment]
Hov. Det ligner en 'sen-nat' fejl. Prøv V1. 0.1.

**Comment by Bluhme1** [comment]
Så kom sensorerne ind 👍 Jeg bruger lige lidt tid på at checke de værdier, der kommer.
Du er sgu skrap !
