### ISSUE TITLE
billing_period_skew error on load

### ISSUE THREAD

**Issue by jolsso** [kpoppel/homeassistant-eforsyning#3]
Hi

There's a problem when loading the module (e.g. restarting Home Assistant) that related to 8d10aa1.

```
Logger: homeassistant.config_entries
Source: custom_components/eforsyning/__init__.py:43 
Integration: EForsyning 
First occurred: 8:16:28 AM (1 occurrences) 
Last logged: 8:16:28 AM

Error setting up entry Eforsyning 8b563ac8-706e-45c6-a23c-a6cabcae3e41 for eforsyning
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 269, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/eforsyning/__init__.py", line 43, in async_setup_entry
    billing_period_skew = entry.data['billing_period_skew'] # This one is true if the billing period is from July to June
KeyError: 'billing_period_skew'
```

**Comment by kpoppel** [comment]
You need to remove the integration and add it again.  The update for 0.3.0 added a new configuration option which is not present in 0.2.0.
The change fixes Issue #1
