### ISSUE TITLE
Fejl efter update til nyeste version

### ISSUE THREAD

**Issue by hedevej41** [kpoppel/homeassistant-eforsyning#33]
Logger: custom_components.eforsyning.coordinator
Source: custom_components/eforsyning/coordinator.py:55
Integration: EForsyning ([documentation](https://github.com/kpoppel/homeassistant-eforsyning), [issues](https://github.com/kpoppel/homeassistant-eforsyning/issues))
First occurred: 17:17:50 (5 occurrences)
Last logged: 17:20:39

Unexpected error fetching eForsyning data: 'NoneType' object has no attribute 'raise_for_status'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.10/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.10/ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api2.dff-edb.dk', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 212, in _get_time_series
    result = requests.post(self._api_server + post_meter_data_url,
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api2.dff-edb.dk', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/eforsyning/coordinator.py", line 53, in _async_update_data
    data = await self.hass.async_add_executor_job(self.api.get_latest)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 353, in get_latest
    raw_data = self._get_time_series(year=year,
  File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 218, in _get_time_series
    raise HTTPFailed(result.raise_for_status())
AttributeError: 'NoneType' object has no attribute 'raise_for_status'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/eforsyning/coordinator.py", line 55, in _async_update_data
    raise ConfigEntryNotReady from error
homeassistant.exceptions.ConfigEntryNotReady: 'NoneType' object has no attribute 'raise_for_status'

**Comment by kpoppel** [comment]
Denne her skyldes at der ikke er svaret fra APIet, og så kommer der et timeout.  Jeg ser på i den kommende release, at der ikke kommer en exception, og at integrationen fejler pænt, og blot returnerer "ukendt" på det tidspunkt. Det bliver v1.0.3
