### ISSUE TITLE
Exception efter opdatering til v1.0.1

### ISSUE THREAD

**Issue by jnxxx** [kpoppel/homeassistant-eforsyning#34]
```
2022-09-05 22:19:39.272 DEBUG (SyncWorker_7) [custom_components.eforsyning.pyeforsyning.eforsyning] Parsing results - billing
2022-09-05 22:19:42.488 ERROR (MainThread) [custom_components.eforsyning.coordinator] Unexpected error fetching eForsyning data: list index out of range
Traceback (most recent call last):
File "/config/custom_components/eforsyning/coordinator.py", line 53, in _async_update_data
data = await self.hass.async_add_executor_job(self.api.get_latest)
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 362, in get_latest
billing_result = self._parse_result_billing(billing_data)
File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 761, in _parse_result_billing
metering_data['amount-remaining'] = self._stof(result[19]['ialt'])
IndexError: list index out of range
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
self.data = await self._async_update_data()
File "/config/custom_components/eforsyning/coordinator.py", line 55, in _async_update_data
raise ConfigEntryNotReady from error
homeassistant.exceptions.ConfigEntryNotReady: list index out of range
2022-09-05 22:19:42.492 DEBUG (MainThread) [custom_components.eforsyning.coordinator] Finished fetching eForsyning data in 7.903 seconds (success: False)
```

Det ser ud til at der hentes noget faktura info:
` result = result['faktlini']`
 
Og der forsøges læst index 19 i dette:
`metering_data['amount-remaining'] = self._stof(result[19]['ialt'])`

Men i mit tilfælde er der kun 15 elementer [0-14].
Jeg ved ikke helt hvad det gør, men der bør nok ledes i det data på en anden måde. Eventuelt efter tekst eller linieType.

**Comment by kpoppel** [comment]
v1.0.2 fikser exception i hvert fald.  Hvis du kan sende dump fra loggen til mig så kan jeg se på hvordan de data så kan parses.  Loggen skulle gerne give en indikation af hvad integrationen ikke forstår.

**Comment by Bluhme1** [comment]
Fik informationer om "billing" i tidligere version. Er nu mærket som ukendt

**Comment by jnxxx** [comment]
Hermed mine data (måler nummer ændret):

```
[
   {
      "ekstra": "kr.",
      "enhedPris": "495,00",
      "linieType": "3",
      "antalEnheder": "3,558",
      "enhed": "MWh",
      "tekst": "12345678",
      "prisEnhed": "kr./MWh",
      "opl4": "MWh",
      "opl3": "15,507",
      "opl2": "MWh",
      "opl1": "11,949",
      "ialt": "1.761,21"
   },
   {
      "ekstra": "",
      "enhedPris": "",
      "linieType": "3",
      "antalEnheder": "31,36",
      "enhed": "°C",
      "tekst": " Afkøling",
      "prisEnhed": "",
      "opl4": "",
      "opl3": "",
      "opl2": "",
      "opl1": "",
      "ialt": ""
   },
   {
      "ekstra": "kr.",
      "enhedPris": "782,40",
      "linieType": "3",
      "antalEnheder": "1,147",
      "enhed": "MWh",
      "tekst": "12345678",
      "prisEnhed": "kr./MWh",
      "opl4": "MWh",
      "opl3": "16,654",
      "opl2": "MWh",
      "opl1": "15,507",
      "ialt": "897,41"
   },
   {
      "ekstra": "",
      "enhedPris": "",
      "linieType": "3",
      "antalEnheder": "20,25",
      "enhed": "°C",
      "tekst": " Afkøling",
      "prisEnhed": "",
      "opl4": "",
      "opl3": "",
      "opl2": "",
      "opl1": "",
      "ialt": ""
   },
   {
      "ekstra": "kr.",
      "enhedPris": "782,40",
      "linieType": "3",
      "antalEnheder": "2,877",
      "enhed": "MWh",
      "tekst": "Prognose: 06-09-2022 til 31-12-2022",
      "prisEnhed": "kr./MWh",
      "opl4": "",
      "opl3": "",
      "opl2": "",
      "opl1": "",
      "ialt": "2.250,96"
   },
   {
      "ekstra": "kr.",
      "enhedPris": "",
      "linieType": "12",
      "antalEnheder": "",
      "enhed": "",
      "tekst": "Samlet varmeforbrug",
      "prisEnhed": "",
      "opl4": "",
      "opl3": "",
      "opl2": "",
      "opl1": "",
      "ialt": "4.909,58"
   },
   {
      "ekstra": "kr.",
      "enhedPris": "3.773,00",
      "linieType": "1",
      "antalEnheder": "",
      "enhed": "",
      "tekst": "Fast bidrag 101 - 150",
      "prisEnhed": "kr./år",
      "opl4": "",
      "opl3": "",
      "opl2": "dage",
      "opl1": "365",
      "ialt": "3.773,00"
   },
   {
      "ekstra": "",
      "enhedPris": "",
      "linieType": "0",
      "antalEnheder": "",
      "enhed": "",
      "tekst": " ",
      "prisEnhed": "",
      "opl4": "",
      "opl3": "",
      "opl2": "",
      "opl1": "",
      "ialt": ""
   },
   {
      "ekstra": "kr.",
      "enhedPris": "",
      "linieType": "12",
      "antalEnheder": "",
      "enhed": "",
      "tekst": "Total (excl. moms)",
      "prisEnhed": "",
      "opl4": "",
      "opl3": "",
      "opl2": "",
      "opl1": "",
      "ialt": "8.682,58"
   },
   {
      "ekstra": "kr.",
      "enhedPris": "8.682,58",
      "linieType": "10",
      "antalEnheder": "25,00",
      "enhed": "%",
      "tekst": "Moms",
      "prisEnhed": "kr.",
      "opl4": "",
      "opl3": "",
      "opl2": "",
      "opl1": "",
      "ialt": "2.170,65"
   },
   {
      "ekstra": "kr.",
      "enhedPris": "",
      "linieType": "12",
      "antalEnheder": "",
      "enhed": "",
      "tekst": "Total (incl.moms.)",
      "prisEnhed": "",
      "opl4": "",
      "opl3": "",
      "opl2": "",
      "opl1": "",
      "ialt": "10.853,23"
   },
   {
      "ekstra": "kr.",
      "enhedPris": "",
      "linieType": "18",
      "antalEnheder": "",
      "enhed": "",
      "tekst": "Opkrævet aconto (incl.moms)",
      "prisEnhed": "",
      "opl4": "",
      "opl3": "",
      "opl2": "",
      "opl1": "",
      "ialt": "-10.900,00"
   },
   {
      "ekstra": "kr.",
      "enhedPris": "",
      "linieType": "12",
      "antalEnheder": "",
      "enhed": "",
      "tekst": "For meget indbetalt",
      "prisEnhed": "",
      "opl4": "",
      "opl3": "",
      "opl2": "",
      "opl1": "",
      "ialt": "46,77"
   },
   {
      "ekstra": "kr.",
      "enhedPris": "",
      "linieType": "20",
      "antalEnheder": "",
      "enhed": "",
      "tekst": "Forventet indbetalt: 06-09-2022 til 31-12-2022",
      "prisEnhed": "",
      "opl4": "",
      "opl3": "",
      "opl2": "",
      "opl1": "",
      "ialt": "-3.920,00"
   },
   {
      "ekstra": "kr.",
      "enhedPris": "",
      "linieType": "12",
      "antalEnheder": "",
      "enhed": "",
      "tekst": "Til udbetaling",
      "prisEnhed": "",
      "opl4": "",
      "opl3": "",
      "opl2": "",
      "opl1": "",
      "ialt": "3.966,77"
   }
]
```

**Comment by kpoppel** [comment]
Tak for det. De 15 linjer er jo noget mindre end de 28 jeg selv får. Jeg prøver at se om der et system i det her.

**Comment by kpoppel** [comment]
@jnxxx Der er to styk MWh-pris og forbrug.  Kan det passe at du har set en prisstigning midt i det hele fra 495 til 782 kr/MWh?  Jeg tænker at regne gennemsnits-prisen pr. MWh ud i det tilfælde.

**Comment by kpoppel** [comment]
Det tog noget tid, men https://github.com/kpoppel/homeassistant-eforsyning/releases/tag/v1.0.4 er ude som pre-release.  Jeg skulle mene at data herover i hvert fald kan parses, også selv-om der er en prisændring i løbet af perioden.
