### ISSUE TITLE
[BUG] KeyError: 'TForbrugsTaellevaerk'

### ISSUE THREAD

**Issue by r-poulsen** [kpoppel/homeassistant-eforsyning#40]
Efter opdatering kører integrationen i ring med beskeden "Forsøger konfigurationen igen: 'TForbrugsTaellevaerk'" og jeg får nedenstående i ha-loggen:

```
2022-10-29 09:25:05.141 ERROR (MainThread) [custom_components.eforsyning.coordinator] Unexpected error fetching eForsyning data: 'TForbrugsTaellevaerk'
Traceback (most recent call last):
  File "/config/custom_components/eforsyning/coordinator.py", line 53, in _async_update_data
    data = await self.hass.async_add_executor_job(self.api.get_latest)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 379, in get_latest
    result = self._parse_result_totals_line(year_data)
  File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 478, in _parse_result_totals_line
    for meter in result['IaltLinje']['TForbrugsTaellevaerk']:
KeyError: 'TForbrugsTaellevaerk'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/eforsyning/coordinator.py", line 55, in _async_update_data
    raise ConfigEntryNotReady from error
homeassistant.exceptions.ConfigEntryNotReady: 'TForbrugsTaellevaerk'
```

**Comment by kpoppel** [comment]
Takker. Har du mulighed for at sende et dump af de JSON data du får på website første gang årsdata vises? Det er dem der hedder noget Meg getForbrug... Eller sådan noget. Har ikke lige en PC med mig 😊 Måske har du ikke disse data, eller tælleværker.

**Comment by r-poulsen** [comment]
Umiddelbart ser det meget tilforladeligt ud:

![billede](https://user-images.githubusercontent.com/2556678/198840818-98c72d18-e87c-4742-b6a4-ddbc8a0bcd75.png)

[getforbrug.txt](https://github.com/kpoppel/homeassistant-eforsyning/files/9894032/getforbrug.txt)

**Comment by r-poulsen** [comment]
Jeg ved ikke om debug loggen måske kan hjælpe. Jeg har fjernet alt der ligner personligt data.

```
2022-10-31 19:02:35.585 DEBUG (MainThread) [custom_components.eforsyning] eForsyning ConfigData: {'username': 'xxx', 'password': 'yyy', 'supplierid': 'AAAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEEEE', 'entityname': 'EForsyning', 'billing_period_skew': False, 'is_water_supply': False}
2022-10-31 19:02:35.586 DEBUG (SyncWorker_9) [custom_components.eforsyning.pyeforsyning.eforsyning] Getting api server at supplier AAAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEEEE
2022-10-31 19:02:35.686 DEBUG (SyncWorker_9) [custom_components.eforsyning.pyeforsyning.eforsyning] Done getting api server https://app-htf.dff-edb.dk:443/htf/
2022-10-31 19:02:35.687 DEBUG (SyncWorker_9) [custom_components.eforsyning.pyeforsyning.eforsyning] Getting access token
2022-10-31 19:02:35.802 DEBUG (SyncWorker_9) [custom_components.eforsyning.pyeforsyning.eforsyning] Got access token: ffffffffffffffffffffffffffffffff
2022-10-31 19:02:35.978 DEBUG (SyncWorker_9) [custom_components.eforsyning.pyeforsyning.eforsyning] Login success
2022-10-31 19:02:35.984 DEBUG (SyncWorker_6) [custom_components.eforsyning.pyeforsyning.eforsyning] Getting latest data
2022-10-31 19:02:35.984 DEBUG (SyncWorker_6) [custom_components.eforsyning.pyeforsyning.eforsyning] Getting userinfo from API (ebrugerinfo)
2022-10-31 19:02:35.984 DEBUG (SyncWorker_6) [custom_components.eforsyning.pyeforsyning.eforsyning] Trying: https://app-htf.dff-edb.dk:443/htf/api/getebrugerinfo?id=ffffffffffffffffffffffffffffffff
2022-10-31 19:02:36.254 DEBUG (SyncWorker_6) [custom_components.eforsyning.pyeforsyning.eforsyning] Response from userinfo API. ebrugerinfo: 200, Body: {"id":1111,"navn":"aaa bbb og","navn2":"ccc ddd","vej":"vvv","husnr":"11","litra":"","litra2":"","postnr":"1111","bynavn":"bbb","email":"","beboeremail":"nnn@nnn.dk","tlf":"1111 2222","rolle":1,"indflyttet":"29-11-2016","notifikationmail":"","notifikationmobil":"","notifikationtype":"","ejendomnr":xxx,"frekvens":0,"overvaagningstypeforbrug":0,"vaerdiforbrug":0,"overvaagningstypeinstallation":0,"vaerdiinstallation":0,"ejerNavn":"aaa bbb og","menupunkter":["fakturagodkendelse","opgaver","noter","mitforbrug","minedokumenter","sammenlignforbrug","mineoplysninger","beskeder","calculatedvarmeregnskab","meldflytning","smsservice","kontakt","indtastaflaesninger"],"huskelisteId":0}, ebruger: 1111
2022-10-31 19:02:36.254 DEBUG (SyncWorker_6) [custom_components.eforsyning.pyeforsyning.eforsyning] Getting installations at supplier: AAAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEEEE
2022-10-31 19:02:36.254 DEBUG (SyncWorker_6) [custom_components.eforsyning.pyeforsyning.eforsyning] Trying: https://app-htf.dff-edb.dk:443/htf/api/FindInstallationer?id=ffffffffffffffffffffffffffffffff
2022-10-31 19:02:37.178 DEBUG (SyncWorker_6) [custom_components.eforsyning.pyeforsyning.eforsyning] Response from API. Status: 200, Body: {"Installationer":[{"EjendomNr":xxx,"Adresse":"vvv 11","InstallationNr":1,"ForbrugerNr":"xxx","MålerNr":"22222222","By":"bbb","PostNr":"1111","AktivNr":1,"Målertype":"Kamstrup 602 - Fremløb"}]}
2022-10-31 19:02:37.178 DEBUG (SyncWorker_6) [custom_components.eforsyning.pyeforsyning.eforsyning] Done getting installatons[0] {'EjendomNr': xxx, 'Adresse': 'vvv 11', 'InstallationNr': 1, 'ForbrugerNr': 'xxx', 'MålerNr': '22222222', 'By': 'bbb', 'PostNr': '1111', 'AktivNr': 1, 'Målertype': 'Kamstrup 602 - Fremløb'}
2022-10-31 19:02:37.178 DEBUG (SyncWorker_6) [custom_components.eforsyning.pyeforsyning.eforsyning] Getting time series
2022-10-31 19:02:37.178 DEBUG (SyncWorker_6) [custom_components.eforsyning.pyeforsyning.eforsyning] POST data to API. {'Ejendomnr': 'xxx', 'AktivNr': '1', 'I_Nr': '1', 'AarsMaerke': 2016, 'ForbrugsAfgraensning_FraDato': '0', 'ForbrugsAfgraensning_TilDato': '0', 'ForbrugsAfgraensning_FraAflaesning': '0', 'ForbrugsAfgraensning_TilAflaesning': '2', 'ForbrugsAfgraensning_MedtagMellemliggendeMellemaflas': 'false', 'Optioner': 'foBestemtBeboer, foSkabDetaljer, foMedtagWebAflaes', 'AHoejDetail': 'false', 'Aflaesningsfilter': 'afMaanedsvis', 'AflaesningsFilterDag': 'ULTIMO', 'AflaesningsUdjaevning': 'false', 'SletFiltreredeAflaesninger': 'true', 'MedForventetForbrug': 'true', 'OmregnForbrugTilAktuelleEnhed': 'true'}
2022-10-31 19:02:37.430 DEBUG (SyncWorker_6) [custom_components.eforsyning.pyeforsyning.eforsyning] Done getting time series 200, Body: {
2022-10-31 19:02:37.430 DEBUG (SyncWorker_6) [custom_components.eforsyning.pyeforsyning.eforsyning] Parsing results - IaltLinje for non-day data.
2022-10-31 19:02:37.432 ERROR (MainThread) [custom_components.eforsyning.coordinator] Unexpected error fetching eForsyning data: 'TForbrugsTaellevaerk'
  File "/config/custom_components/eforsyning/coordinator.py", line 53, in _async_update_data
  File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 379, in get_latest
  File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 478, in _parse_result_totals_line
  File "/config/custom_components/eforsyning/coordinator.py", line 55, in _async_update_data
2022-10-31 19:02:37.441 DEBUG (MainThread) [custom_components.eforsyning.coordinator] Finished fetching eForsyning data in 1.855 seconds (success: False)

```

**Comment by r-poulsen** [comment]
Jeg tror at jeg har fundet noget. Jeg har ikke data fra 2016 og tidligere på eforsyning.dk. Vi skiftede vist nok varmeværk i 2016. Det svarer også til "indflyttet" feltet i userinfo API responsen. 

![billede](https://user-images.githubusercontent.com/2556678/199090298-df9d789d-e27f-448d-a7e5-ce9e261e98c0.png)

**Comment by kpoppel** [comment]
Ok takker for detaljerne.  Jeg tror jeg ved hvad der er i vejen.  Jeg kæmper med lidt Internetproblemer disse dage, men ser på det snarest.

**Comment by r-poulsen** [comment]
Fixet i 1.1.1 👍
