### ISSUE TITLE
[BUG] Integration stopped working and can't reinstall it.

### ISSUE THREAD

**Issue by mm98** [kpoppel/homeassistant-eforsyning#65]
Please help me help you:

- [x] Describe what you experience and what the expectation was
- [x] Describe reproduction steps (if something special was done)
- [x] Did you try to add the debug lines to configuration.yaml? Post the output please.
- [x] If relevant, please post screenshots

## Describe the bug
This integration has been working flawlessly for a long time. The last two days it started failing. I've validated my credentials and supplierId which are correct. I removed the device and tried to install it again. Which just returns an `unknown` error.

![image](https://github.com/kpoppel/homeassistant-eforsyning/assets/992714/3b027625-bbc8-41f0-bea6-d3a81fb36917)

## To Reproduce
It is hard to describe, what is causing this. I have supplied the debug logs below. From the logs it almost looks like a request URL isn't constructed correctly `exceptions.MissingSchema`, but everyone else would also have this problem then - which it doesn't look like.

## Expected behavior
It works like it used to? 😄

## Log file output

Reloading the existing integration that is suddenly failing, with `debug` enabled (in UI):

```
2024-05-25 08:03:24.749 ERROR (MainThread) [custom_components.eforsyning.coordinator] Some error occurred!
2024-05-25 08:03:24.758 ERROR (MainThread) [custom_components.eforsyning.coordinator] Unexpected error fetching eForsyning data
Traceback (most recent call last):
  File "/config/custom_components/eforsyning/coordinator.py", line 53, in _async_update_data
    data = await self.hass.async_add_executor_job(self.api.get_latest)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 403, in get_latest
    self._get_ebrugerinfo()
  File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 59, in _get_ebrugerinfo
    result = requests.get(userinfoURL,
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'api/getebrugerinfo?id=': No scheme supplied. Perhaps you meant https://api/getebrugerinfo?id=?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eforsyning/coordinator.py", line 55, in _async_update_data
    raise ConfigEntryNotReady from error
homeassistant.exceptions.ConfigEntryNotReady: Invalid URL 'api/getebrugerinfo?id=': No scheme supplied. Perhaps you meant https://api/getebrugerinfo?id=?
```

With logger `debug` enabled in `configuration.yaml` (trying to reinstall the integration)

```
2024-05-25 09:25:35.506 DEBUG (MainThread) [custom_components.eforsyning.config_flow] Setup Step User_input = {'username': '{REDACTED}', 'password': '{REDACTED}', 'supplierid': '{REDACTED}', 'entityname': 'EForsyning', 'billing_period_skew': False, 'is_water_supply': False}
2024-05-25 09:25:35.507 DEBUG (SyncWorker_3) [custom_components.eforsyning.pyeforsyning.eforsyning] Getting api server at supplier {REDACTED}
2024-05-25 09:25:35.722 ERROR (MainThread) [custom_components.eforsyning.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 4 column 1 (char 6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/eforsyning/config_flow.py", line 73, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eforsyning/config_flow.py", line 44, in validate_input
    await hass.async_add_executor_job(api.authenticate)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 381, in authenticate
    self._get_api_server()
  File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 321, in _get_api_server
    result_json = result.json()
                  ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 4 column 1 (char 6)
```

## Debug log file
[home-assistant_eforsyning_2024-05-25T06-23-56.289Z.log](https://github.com/kpoppel/homeassistant-eforsyning/files/15442015/home-assistant_eforsyning_2024-05-25T06-23-56.289Z.log)

**Comment by mm98** [comment]
I just noticed the pull request #64. This solved the challenge reported above. Closing this.

**Comment by kpoppel** [comment]
Great. I will make a release of this.
